import React, {Component} from "react";

class Hjem extends Component{
  render(){
    return(
      <div align="center" className="jumbotron jumbotron-fluid">
        <h2>HELLO WORLD</h2>
        <hr className="my-4"></hr>
        <div className="badge badge-primary text-wrap">
        <p className="text-justify break-word "> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Est velit egestas dui id ornare arcu odio ut sem. Ornare arcu dui vivamus arcu felis. Felis bibendum ut tristique et egestas quis ipsum suspendisse. In mollis nunc sed id semper risus in. Vitae tortor condimentum lacinia quis vel eros donec ac odio. Varius quam quisque id diam vel quam. Diam volutpat commodo sed egestas egestas fringilla. Est sit amet facilisis magna etiam tempor orci. Risus in hendrerit gravida rutrum quisque. Commodo quis imperdiet massa tincidunt nunc pulvinar. Semper quis lectus nulla at volutpat. Vulputate dignissim suspendisse in est. Vel elit scelerisque mauris pellentesque pulvinar. Sit amet volutpat consequat mauris nunc congue. Gravida dictum fusce ut placerat orci. Sed egestas egestas fringilla phasellus faucibus scelerisque.
Interdum velit laoreet id donec. Aliquet enim tortor at auctor urna nunc id cursus metus. Facilisi cras fermentum odio eu feugiat pretium nibh. Risus sed vulputate odio ut enim blandit volutpat maecenas. Habitant morbi tristique senectus et netus et malesuada fames. Nulla porttitor massa id neque aliquam vestibulum. Volutpat commodo sed egestas egestas fringilla phasellus. Id interdum velit laoreet id donec. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Tellus at urna condimentum mattis pellentesque id nibh tortor id.</p></div>
<div className="badge badge-secondary text-wrap">
<p>Tristique senectus et netus et malesuada fames ac turpis. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Dictum varius duis at consectetur lorem donec. Lobortis feugiat vivamus at augue eget arcu dictum. Bibendum at varius vel pharetra. Tristique senectus et netus et malesuada fames ac. Turpis egestas integer eget aliquet nibh praesent tristique. Sed nisi lacus sed viverra tellus in hac habitasse platea. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Lectus sit amet est placerat in. Sed sed risus pretium quam. Etiam dignissim diam quis enim lobortis. Vitae sapien pellentesque habitant morbi. Lorem ipsum dolor sit amet consectetur adipiscing. Magna sit amet purus gravida quis blandit turpis cursus. Etiam tempor orci eu lobortis elementum nibh tellus molestie. Proin sagittis nisl rhoncus mattis rhoncus urna. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Porta lorem mollis aliquam ut porttitor leo.
Ut consequat semper viverra nam libero justo laoreet sit. Integer eget aliquet nibh praesent tristique magna. Feugiat in fermentum posuere urna nec. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ornare suspendisse sed nisi lacus. Sed vulputate odio ut enim blandit. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Lorem ipsum dolor sit amet. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Orci eu lobortis elementum nibh tellus molestie nunc. Sit amet nulla facilisi morbi. Ut diam quam nulla porttitor massa id. Ac feugiat sed lectus vestibulum mattis. Purus faucibus ornare suspendisse sed nisi. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Ipsum dolor sit amet consectetur adipiscing.</p>
</div>
<div className="badge badge-primary text-wrap">
<p>Morbi leo urna molestie at elementum eu facilisis. Id aliquet risus feugiat in ante metus dictum. Tincidunt eget nullam non nisi. Feugiat sed lectus vestibulum mattis ullamcorper velit. Est velit egestas dui id ornare. Nunc mattis enim ut tellus. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Nec feugiat in fermentum posuere urna nec tincidunt. Est sit amet facilisis magna etiam tempor. Rutrum quisque non tellus orci ac auctor augue mauris. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Neque vitae tempus quam pellentesque nec nam. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium.
Lorem sed risus ultricies tristique nulla. Egestas dui id ornare arcu odio. Quam nulla porttitor massa id neque. Feugiat vivamus at augue eget arcu. Volutpat diam ut venenatis tellus in metus vulputate. Condimentum lacinia quis vel eros donec ac odio tempor. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Enim ut sem viverra aliquet eget sit amet tellus. Enim sed faucibus turpis in eu mi bibendum. Faucibus et molestie ac feugiat sed lectus vestibulum. Fringilla phasellus faucibus scelerisque eleifend. Sodales ut etiam sit amet nisl purus in. Sed adipiscing diam donec adipiscing.
Nullam vehicula ipsum a arcu cursus. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Risus pretium quam vulputate dignissim suspendisse in est. Justo eget magna fermentum iaculis. Quam quisque id diam vel quam elementum pulvinar etiam non. At elementum eu facilisis sed odio morbi quis. Nibh sit amet commodo nulla facilisi. Enim diam vulputate ut pharetra. Lobortis elementum nibh tellus molestie nunc. Ac tortor dignissim convallis aenean. Pretium lectus quam id leo in vitae turpis massa.</p></div>
<div className="badge badge-secondary text-wrap py-3" >
<p>Magna sit amet purus gravida quis blandit turpis cursus in. Pellentesque dignissim enim sit amet venenatis urna. Odio morbi quis commodo odio aenean sed. Aliquam faucibus purus in massa tempor. Aliquet lectus proin nibh nisl condimentum id. Ultrices eros in cursus turpis. Malesuada proin libero nunc consequat interdum. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Ridiculus mus mauris vitae ultricies leo integer. Dictum sit amet justo donec enim diam vulputate ut pharetra. Cras semper auctor neque vitae tempus quam pellentesque nec. Dictum at tempor commodo ullamcorper a lacus vestibulum sed. Urna molestie at elementum eu facilisis sed odio morbi.
Turpis in eu mi bibendum neque egestas. Eros in cursus turpis massa tincidunt dui ut. Sed blandit libero volutpat sed. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Odio ut sem nulla pharetra diam. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Neque aliquam vestibulum morbi blandit cursus risus at. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Ut porttitor leo a diam sollicitudin tempor id. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Auctor elit sed vulputate mi. In eu mi bibendum neque egestas congue quisque. Duis at tellus at urna condimentum. Dapibus ultrices in iaculis nunc sed. Mi quis hendrerit dolor magna eget est lorem.
Egestas sed tempus urna et pharetra pharetra massa massa. Turpis cursus in hac habitasse. Sagittis aliquam malesuada bibendum arcu. Vitae congue eu consequat ac felis donec et odio. Faucibus vitae aliquet nec ullamcorper sit. Nibh cras pulvinar mattis nunc sed blandit. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Leo integer malesuada nunc vel risus commodo viverra. Arcu bibendum at varius vel pharetra vel. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Tempor id eu nisl nunc mi. </p>
      </div>
    </div>

    )
  }
}
export default Hjem;
